

site_name: Python on whales
docs_dir: generated_sources
repo_url: "https://github.com/gabrieldemarmiesse/python-on-whales"
site_description: 'Python on whales docs'

theme:
  name: material

markdown_extensions:
- pymdownx.snippets:
    check_paths: true

plugins:
  - search
  - autorefs
  - mkdocstrings:
      custom_templates: templates
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            show_bases: false
            show_root_heading: true
            show_source: false
            group_by_category: true
            show_category_heading: false
            heading_level: 1
            show_root_toc_entry: false
            separate_signature: true
            merge_init_into_class: false
            show_root_full_path: false
            docstring_options:
              ignore_init_summary: false
nav:
  - Docker client: docker_client.md
  - Sub-commands:
    - docker buildx: sub-commands/buildx.md
    - docker compose: sub-commands/compose.md
    - docker config: sub-commands/config.md
    - docker container: sub-commands/container.md
    - docker context: sub-commands/context.md
    - docker image: sub-commands/image.md
    - docker manifest: sub-commands/manifest.md
    - docker network: sub-commands/network.md
    - docker node: sub-commands/node.md
    - docker plugin: sub-commands/plugin.md
    - docker secret: sub-commands/secret.md
    - docker service: sub-commands/service.md
    - docker stack: sub-commands/stack.md
    - docker swarm: sub-commands/swarm.md
    - docker system: sub-commands/system.md
    - docker task: sub-commands/task.md
    - docker trust: sub-commands/trust.md
    - docker volume: sub-commands/volume.md
  - Docker objects:
    - Builders: docker_objects/builders.md
    - Configs: docker_objects/configs.md
    - Containers: docker_objects/containers.md
    - Images: docker_objects/images.md
    - Networks: docker_objects/networks.md
    - Nodes: docker_objects/nodes.md
    - Plugins: docker_objects/plugins.md
    - Secrets: docker_objects/secrets.md
    - Services: docker_objects/services.md
    - Stacks: docker_objects/stacks.md
    - Tasks: docker_objects/tasks.md
    - Volumes: docker_objects/volumes.md
  - User guide:
      - docker.run() guide: user_guide/docker_run.md
      - Swarm generic resources: user_guide/generic_resources.md
      - Running python-on-whales inside a container: user_guide/running_python_on_whales_inside_a_container.md
      - dealing with exceptions: user_guide/exceptions.md
