

site_name: Python on whales
docs_dir: generated_sources
site_description: 'Python on whales docs'

nav:
  - Docker client: docker_client.md
  - Sub-commands:
    - Buildx: sub-commands/buildx.md
    - Container: sub-commands/container.md
    - Image: sub-commands/image.md
    - Node: sub-commands/node.md
    - Network: sub-commands/network.md
    - Service: sub-commands/service.md
    - Volume: sub-commands/volume.md
  - Docker objects:
    - Builders: docker_objects/builders.md
    - Containers: docker_objects/containers.md
    - Images: docker_objects/images.md
    - Networks: docker_objects/networks.md
    - Nodes: docker_objects/nodes.md
    - Services: docker_objects/services.md
    - Volumes: docker_objects/volumes.md
