

site_name: Python on whales
docs_dir: generated_sources
site_description: 'Python on whales docs'

nav:
  - Docker client: docker_client.md
  - Sub-commands:
    - docker buildx: sub-commands/buildx.md
    - docker container: sub-commands/container.md
    - docker image: sub-commands/image.md
    - docker node: sub-commands/node.md
    - docker network: sub-commands/network.md
    - docker service: sub-commands/service.md
    - docker swarm: sub-commands/swarm.md
    - docker system: sub-commands/system.md
    - docker volume: sub-commands/volume.md
  - Docker objects:
    - Builders: docker_objects/builders.md
    - Containers: docker_objects/containers.md
    - Images: docker_objects/images.md
    - Networks: docker_objects/networks.md
    - Nodes: docker_objects/nodes.md
    - Services: docker_objects/services.md
    - Volumes: docker_objects/volumes.md
